name: github pages

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest
      
      - name: Document rust code
        run: cargo doc --workspace

      - run: mdbook build
        working-directory: ./docs

      - name: Copy artifacts
        run: |
          mkdir dist
          cp -r ./docs/book dist/book
          cp -r ./target/doc dist/doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
